export default {
  instrument: {
    classic: 'Guitar',
    lapsteel: 'Lapsteel Guitar',
    bass: 'Bass Guitar',
    ukulele: 'Ukulele',
  },
  displayMode: {
    note: 'Notes',
    interval: 'Intervals',
    both: 'Notes & intervals',
  },
  modes: {
    chromatic: 'Chromatic',
    major: 'Major',
    majorPentatonic: 'Major Pentatonic',
    minor: 'Minor',
    minorPentatonic: 'Minor Pentatonic',
    minorHarmonic: 'Minor Harmonic',
    minorMelodic: 'Minor Melodic',
    alteredDominant: 'Altered Dominant',
    blues: 'Blues',
    dorian: 'Dorian',
    locrian: 'Locrian',
    lydian: 'Lydian',
    myxolidian: 'Myxolidian',
    phrygian: 'Phrygian',
  },
  intervals: {
    T: 'Tonic',
    b2: 'Minor second',
    M2: 'Major second',
    b3: 'Minor third',
    M3: 'Major third',
    P4: 'Perfect fourth',
    b5: 'Diminished fifth',
    P5: 'Perfect fifth',
    b6: 'Minor sixth',
    M6: 'Major sixth',
    b7: 'Minor seventh',
    M7: 'Major seventh',
  },
  form: {
    diplayIntervals: 'Display intervals',
  },
};
